### ISSUE TITLE
a2 question

### ISSUE THREAD

**Issue by rafita275** [rhodyprog4ds/BrownFall22#2]
In the assignment 2, in the section that says make a dataset of dataset. What is IT referring to in the phrase: Then iterate over the list of dictionaries, and:  save IT to a local csv using the short name you provided for the dataset as the file name, without writing the index column to the file. I don't understand what I have to do here.

**Comment by brownsarahm** [comment]
@rafita275 see the additions (highlighted in green) that I have made in the link above and let me know if that helps

**Comment by rafita275** [comment]
I'm sorry, but I think I'm more confused now. Could you explain each point you mentioned: link glossary, add hints, etc., a bit more in-depth because, for example, I don't know which link glossary you are referring to. I just want to do well in this class and understand everything nicely.

**Comment by rafita275** [comment]
Professor the thing is that I don't undertand what 'link glossary, add
hints and make explicit and implied step' means. Like how I do that? Could
you explain it to me again please?
Thank you very much
Rafael

**Comment by rafita275** [comment]
I don't see any higlight in green neither I can't find that. Sorry for that
but I a'm also having some difficulties to undertand how github works.
Once again thenk you.
Rafael

**Comment by brownsarahm** [comment]
What you quoted was my summary of the changes. Reading replies in email does not show you the whole thing, you needed to click on that link.  Your response took a while, so I posted the changes to the website to help others. Please reread the assignment text (after refreshing the page) and open a new ussue if you still have questions

**Comment by rafita275** [comment]
Thank you for the clarification.
