### ISSUE TITLE
Confusion on Assignment 7

### ISSUE THREAD

**Issue by dsdelgiudice** [rhodyprog4ds/BrownFall22#34]
@brownsarahm @aHill024 
For assignment 7, the directions on step 4 in section 7.2 are a bit confusing. The directions say to repeat the train test split 5 times. Exactly what are supposed to base on the repetition on? Are we supposed to repeat the train test split on the different sizes for the X_train DataFrame (Similar to step 1 in section 7.3), or are we supposed to perform the T.T. split on different samples (via a different random state parameter each time)?

**Comment by brownsarahm** [comment]
yes different random samples, do not fix the `random_state` parameter
