### ISSUE TITLE
A2: more detail on the dictionary 

### ISSUE THREAD

**Issue by sdzwil** [rhodyprog4ds/BrownFall22#6]
Under 2.4. Store them for loading, it says "Each dictionary should have the following keys:" and I don't see where the following keys are listed.

**Comment by sdzwil** [comment]
Can you please add a description of what the keys should be? What should "load_func" be in the datasets.py file?

**Comment by brownsarahm** [comment]
Good catch, I wrote a table with the information and something went wrong so it's not visible on the rendered website for now, look here : https://github.com/rhodyprog4ds/BrownFall22/blob/main/assignments/02-python-access.md#store-them-for-loading

And I'll get that fixed

**Comment by sdzwil** [comment]
Thank you!
